// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbw1liDBQXJ1lUrsDTI4Bnr_qIk5s0ofs',
    appId: '1:1004810980308:web:e3e649e4aa609fc1a22441',
    messagingSenderId: '1004810980308',
    projectId: 'hio-candidate',
    authDomain: 'hio-candidate.firebaseapp.com',
    storageBucket: 'hio-candidate.appspot.com',
    measurementId: 'G-9ET2TQZWQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAlKr9jEiJOWYfeZH2gJBsazQj-rJe7g',
    appId: '1:1004810980308:android:d9e4ad2db605cbb0a22441',
    messagingSenderId: '1004810980308',
    projectId: 'hio-candidate',
    storageBucket: 'hio-candidate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJNo5GCQ47CxXc8F0O4WMp72NdYgLKQDk',
    appId: '1:1004810980308:ios:8be9b3d6deba4434a22441',
    messagingSenderId: '1004810980308',
    projectId: 'hio-candidate',
    storageBucket: 'hio-candidate.appspot.com',
    iosClientId: '1004810980308-lnsl9i76ar2u38daujf3jfgf1j0cja4i.apps.googleusercontent.com',
    iosBundleId: 'com.hio.candidate',
  );
}
